### ISSUE TITLE
滚动有点不流畅诶..

### ISSUE THREAD

**Issue by elegy7** [alanchenchen/v-scroller#1]
是不是可以优化下呢

**Comment by alanchenchen** [comment]
emmmmm,是不是你在scroller里写了太多内容啊，或者是事件重叠了，这个插件已经用了css3的transform的硬件加速了。在低端机上，如果你不使用太多的嵌套scroller应该不会太卡。。。我之前项目实测过。

**Comment by elegy7** [comment]
并不是动画不流畅, 而是, 手指滑动的时候, 松开后的惯性滚动不自然, 有时候会骤然停止, 另外最近的1.2.5的版本感觉样式有点乱..

**Comment by alanchenchen** [comment]
首先，这个插件的惯性滚动是通过transition实现的，不是用运动函数，所以运动做不到那么自然，另外，样式没问题啊，你得注意把所有reset的样式去除掉margin和padding，手机浏览器默认也会让document存在滚动条，建议禁止掉document滚动条，这样才能最大程度模拟出app的体验
